// <auto-generated />
namespace Home_Shoppe.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class edit_prodct : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(edit_prodct));
        
        string IMigrationMetadata.Id
        {
            get { return "202206241138052_edit_prodct"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
